version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ecocomfort-postgres
    environment:
      POSTGRES_DB: ecocomfort
      POSTGRES_USER: ecocomfort
      POSTGRES_PASSWORD: ecocomfort_secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: