export enum BadgeType {
  FIRST_WEEK = 'FIRST_WEEK',
  QUICK_CLOSE = 'QUICK_CLOSE',
  ENERGY_SAVER = 'ENERGY_SAVER',
  WINTER_GUARDIAN = 'WINTER_GUARDIAN',
  NIGHT_WATCH = 'NIGHT_WATCH',
  PERFECT_DAY = 'PERFECT_DAY'
}